### ISSUE TITLE
Adding support for Runes?

### ISSUE THREAD

**Issue by Morgandri1** [bitfinity-network/ord-rs#12]
**Is your feature request related to a problem? Please describe.**
As of today, the runes standard has been merged into `ord/main`. I'd like to use this library to use the new standard

**Describe the solution you'd like**
Adding support for runes from ord

**Describe alternatives you've considered**
It seems like the only other alternative is to rig it all together through standard ordinals code

**Comment by blutooth** [comment]
Runes support has been added. https://github.com/bitfinity-network/ord-rs/pull/19

**Comment by Morgandri1** [comment]
Thank you!
